const List<String> travelKeywords = [
  '🏃 Adventure',
  '🧘 Relaxation', 
  '🏙️ Street Culture',
  '🎉 Unique Experiences',
  '🏛️ Landmarks',
  '🌆 Local Vibe',
  '🎭 Cultural',
  '🌿 Nature',
  '🍽️ Food',
  '🏛️ History',
  '🗿 Historical Sites',
  '🏖️ Coastal',
  '💑 Romantic',
];